import enum

class UserRole(str, enum.Enum):
    EMPLOYEE = "EMPLOYEE"
    REVIEWER = "REVIEWER"
    CONTROLLER = "CONTROLLER"

class ClaimStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    RESUBMITTED = "RESUBMITTED"
    APPROVED = "APPROVED"
    FINALIZED = "FINALIZED"
    REJECTED = "REJECTED"
    AMENDMENT_PENDING = "AMENDMENT_PENDING"

class AuditAction(str, enum.Enum):
    CLAIM_CREATED = "CLAIM_CREATED"
    CLAIM_SUBMITTED = "CLAIM_SUBMITTED"
    EVIDENCE_ATTACHED = "EVIDENCE_ATTACHED"
    EVIDENCE_REUSE_FLAGGED = "EVIDENCE_REUSE_FLAGGED"
    CLAIM_REVIEWED = "CLAIM_REVIEWED"
    CLAIM_FINALIZED = "CLAIM_FINALIZED"
    AMENDMENT_CREATED = "AMENDMENT_CREATED"
    CLAIM_EDITED = "CLAIM_EDITED"
    EVIDENCE_REMOVED = "EVIDENCE_REMOVED"
    EXTERNAL_VALIDATION_TRIGGERED = "EXTERNAL_VALIDATION_TRIGGERED"
